<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/482cf5b577.js" crossorigin="anonymous"></script>
    
    <link rel="icon" type="image/png" href="./image/logo.png" />
    <meta name="description" content="Thomas Testaud est un Développeur Web Junior sur Annecy à la recherche d'un premier emploi, stage ou alternance.">
    <meta name='robots' content='index,follow'>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    
    <title>Thomas Testaud</title>
</head>

<body style="overflow: hidden;">
    <main>
        
        <?php require $template; ?>
    </main>
<script src="main.js"></script>
</body>
</html>