<article id="target-up-1" class="landing">
        <?php require 'functions/mail.php' ?>
        <div class="main-element">
            <div class="heading">
                <h1>Thomas Testaud</h1>
                <p>Développeur PHP Junior</p>
            </div>
            <p style="display:none;">À la recherche d'un premier <strong>emploi</strong>, 
                <span class="alternance">
                    <strong>
                        alternance
                        <span class="infoheading">
                            <i class="fa-solid fa-circle-info"></i>
                        </span>
                    </strong> ou 
                </span>
                <span class="stage">
                    <strong>
                        stage
                        <span class=" infoheading">
                            <i class="fa-solid fa-circle-info"></i>
                        </span>
                    </strong>
                </span>
                    <div class="alter-pop none pop-up">
                        <i id="cross-alter" class="fa-solid fa-circle-xmark fa-1x"></i>
                        <p>Alternance de 1 an au rythme de 3 semaines en entreprise et 1 semaines en cours</p>
                    </div>
                    <div class="stage-pop none pop-up">
                        <i id="cross-stage" class="fa-solid fa-circle-xmark fa-1x"></i>
                        <p>Stage convetionné de 3 mois en entreprise</p>
                    </div>
            </p>
        </div>
        
        <div class="about">
            <div class="card-about-1"><p>26 ans</p></div>
            <div class="card-about-2"><p>Disponible en présentiel sur Annecy et les régions avoisinantes</p></div>
            <div class="card-about-3"><p>Disponible partout en télétravail</p></div>
            <div class="card-about-4"><p>Dominance Back-End : PHP</p></div>
            <div class="card-about-5"><p>Maîtrise des languages HTML, CSS, JavaScript, PHP et MySQL</p></div>
            <div class="space"></div>
            <div class="card-about-6"><p>Compétant en Programmation Orienté Objet</p></div>
            <div class="card-about-7"><p>Connaissances en Symfony</p></div>
            <div class="card-about-8"><p>Anglais niveau C1 (bilingue)</p></div>
            <div class="card-about-9"><p>Passionné, sérieux et travailleur</p></div>
        </div>
        
        
        <div class="form">
            <form action="" method="post">
                <h4>Contactez-moi !</h4>
                <input placeholder="Nom/prénom" type="text" name="name">
                <input placeholder="e-mail" type="text" name="email">
                <textarea placeholder="Votre message..." name="message"></textarea>
                <input class="submit" type="submit" value="Envoyer">
            </form>
            <div>
                <p>Ou appelez-moi au</p>
                <a href="tel:0677984857"><p class="phone">06 77 98 48 57</p></a>
                
            </div>
        </div>
        
        <nav id="scroll-down-1" class="scroll-down"><i class="fa-solid fa-arrow-down"></i></nav>
</article>