
<div class="top">
    <a href="?page=home">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" /></svg>
    </a>
</div>

<div class="main">
    <h2>Add Stuff.</h2>
    <form name="addForm" method="post" action="#">
        <input name="newWord" type="text">
        <h2>=</h2>
        <input name="newGuess" type="text">
        <button type="submit">Add</button>
    </form>
</div>